### ISSUE TITLE
a.exe file is missing

### ISSUE THREAD

**Issue by Vasan-jk** [mackorone/mms-c#2]
since a.exe file is missing I could not run the program

**Comment by bavixz** [comment]
yeah a.exe not found

**Comment by mackorone** [comment]
What is your algorithm config? Did you choose the correct directory? Did you build the 'a.exe' program before attempting to run it?

**Comment by mackorone** [comment]
I'm going to close this issue since it's a bit stale. Feel free to reopen if you're still encountering errors.
